apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: kubeflow
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded credentials
  aws-access-key-id: <base64-encoded-access-key>
  aws-secret-access-key: <base64-encoded-secret-key>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-config
  namespace: kubeflow
data:
  s3-bucket: "your-s3-bucket-name"
  s3-key: "models/iris"