model:
  algorithm: "random_forest"  # random_forest, xgboost, logistic_regression, svm
  
  hyperparameters:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
      n_jobs: -1
    
    xgboost:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
    
    logistic_regression:
      C: 1.0
      max_iter: 1000
      random_state: 42
      n_jobs: -1

training:
  optimization:
    method: "grid_search"  # grid_search, random_search, bayesian
    cv_folds: 5
    scoring: "f1_macro"
    n_iter: 50  # for random_search
  
  early_stopping:
    enabled: false
    patience: 10
    min_delta: 0.001

mlflow:
  experiment_name: "ml-e2e-classification"
  tracking_uri: "http://mlflow-server:5000"
  artifact_location: "s3://ml-e2e-project-artifacts/mlflow/"
  
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - roc_auc
  
  plots:
    - confusion_matrix
    - feature_importance
    - roc_curve
    - precision_recall_curve

deployment:
  model_name: "classification_model"
  model_stage: "staging"  # staging, production
  model_version: "latest"